version: 2
jobs:
  build:
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            . setup.env
            just test
