version: 2
jobs:
  build:
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --recursive --init

      - setup_remote_docker

      - run:
          name: Install test dependencies and smuggle vsi to host
          command: |
            apk add --no-cache perl jq
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            . setup.env
            just build recipes
            tar c . | docker run -i --rm -v /root/repo:/src -w /src alpine:3.8 tar x

      - run:
          name: Run unit tests
          environment:
            LDCONFIG: /usr/glibc-compat/sbin/ldconfig
          command: |
            . setup.env
            just test

      - run:
          name: Run integration tests
          command: |
            . setup.env
            just test int
