version: 2
jobs:
  build:
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Checkout submodule
          command: git submodules update --recursive --init

      - run:
          name: Install test dependencies
          command: apk add --no-cache perl

      - setup_remote_docker

      - run:
          name: Run unit tests
          environment:
            LDCONFIG: /usr/glibc-compat/sbin/ldconfig
          command: |
            . setup.env
            just test

      - run:
          name: Run integration tests
          command: |
            . setup.env
            just build recipes
            just testint
