version: 2
jobs:
  build:
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install test dependencies
          command: apk add --no-cache perl

      - run:
          name: run tests
          environment:
            LDCONFIG: /usr/glibc-compat/sbin/ldconfig
          command: |
            . setup.env
            just test
